# Set by github - do not change.
safe: true
lsi: false
highlighter: rouge

exclude:
- bower.json
- bower_components
- Gemfile
- Gemfile.lock

title: Ainex
description: >
  Ainex is a fork of Xenia, the BSD licensed open source research project
  for emulating Xbox 360 games on modern PCs.
url: "https://ainex-project.github.io/"
github_username:  ainex-project

markdown: kramdown

gems:
- jemoji
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap

navigation:
  - pages:
    - title: Home
      path: index.html
    - path: about.md
    - title: Quickstart
      url: https://ainex-project.github.io/wiki/faq/quickstart
      icon: assignment
    - title: Download
      url: https://github.com/ainex-project/ainex
      icon: file_download
    - title: FAQ
      url: https://ainex-project.github.io/wiki/faq
      icon: help
    - title: Roadmap
      url: https://ainex-project.github.io/wiki/faq/roadmap
      icon: event
    - title: Compatibility
      url: https://github.com/ainex-project/game-compatibility/issues
      icon: insert_chart
    - path: gallery.html
# - title: Community
#   pages:
#   - title: Subreddit
#     url: https://www.reddit.com/r/ainex
#     icon: forum
#   - title: YouTube
#     url: https://www.youtube.com/channel/...
#     icon: videocam
  - title: Development
    pages:
    - title: Development Wiki
      url: https://ainex-project.github.io/wiki/development/
      icon: build
    - title: Source Code
      url: https://github.com/ainex-project/ainex
      icon: code
    - title: Issues
      url: https://github.com/ainex-project/ainex/issues
      icon: bug_report

# artifacts:
#   - title: Windows 7+ x64 (Direct3D 12 or Vulkan on Windows 10, Vulkan on Windows 7+)
#     icon: windows
#     branches:
#     - name: main
#       title: main
#       download_url: ""
